# Generated by Django 5.0.6 on 2024-06-08 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
#from validators import validate_name, validate_passport_number


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    
    operations = [
        migrations.CreateModel(
            name='Guest_Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_account.student', verbose_name='Студент')),
                ('guest_name', models.CharField(verbose_name='Имя гостя', max_length=100)), #validators = [validate_name])),
                ('guest_passport', models.IntegerField(verbose_name='Паспорт гостя')), #validators = [validate_passport_number])),
                ('guest_arrival', models.DateTimeField(verbose_name='Время захода гостя')),
                ('guest_departure', models.DateTimeField(verbose_name='Время выхода гостя', null=True, blank=True)),
                ('created_at', models.DateTimeField(verbose_name='Создано', auto_now_add=True))
            ],
        ),
    ]
