# Generated by Django 5.0.7 on 2024-07-14 21:30

import django.db.models.deletion
import invite_guest.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRequest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, validators=[invite_guest.validators.validate_name])),
                ('guest_passport', models.IntegerField(validators=[invite_guest.validators.validate_passport_number])),
                ('guest_arrival', models.DateTimeField()),
                ('guest_departure', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_account.student', verbose_name='Студент')),
            ],
        ),
    ]
