# Generated by Django 5.0.6 on 2024-07-14 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0002_remove_student_user_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=0, max_length=100, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
