# Generated by Django 5.0.6 on 2024-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('student_name', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('status', models.CharField(choices=[('New', 'Новый'), ('In_progress', 'В работе'), ('Completed', 'Завершен')], default='New', max_length=50)),
                ('priority', models.IntegerField(choices=[(1, 'Высокий'), (2, 'Средний'), (3, 'Низкий')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
