# Generated by Django 5.0.6 on 2024-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_bookingcoworking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcoworking',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
